# Site
name: "어디에 추가가 될까요?"
title: "잔디가 심길까요?"
description: "Testing blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
# url: "https://blooming-daisy.github.io/"
baseurl: "https://blooming-daisy.github.io/"
# google_analytics: 'UA-46278016-1'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
utterances:
  enable : true
  repo : blooming-daisy/blooming-daisy.github.io
  issue-term : pathname
  theme : preferred-color-scheme






# Authors
authors:
  Leena:
    name: Leena
    display_name: Leena
    avatar: "assets/images/avatar.jpg"
    email: leenagohk@gmail.com
    instagram: https://www.instagram.com/leena_loves_palmtrees/
    description: "Be positive!!!!!"

# john:
#     name: John
#     display_name: John    
#     avatar: 'assets/images/avatar.png'
#     gravatar: b1cc14991db7a456fcd761680bbc8f81
#     email: wowthemesnet@gmail.com
#     web: https://www.wowthemes.net
#     twitter: https://twitter.com/wowthemesnet
#     description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."




# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
